theme =  "rose_pine"

[editor]
idle-timeout = 20
completion-trigger-len = 1
line-number = "relative"
bufferline = "always"
cursorline = true
color-modes = true

[editor.cursor-shape]
select = "block"
insert = "bar"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"

[keys.normal]
"0" = ["goto_line_start"]
"$" = ["goto_line_end"]
"esc" = ["collapse_selection","keep_primary_selection"]
