theme =  "nord"

[editor]
idle-timeout = 0
completion-trigger-len = 1
true-color = true
line-number = "relative"

[editor.cursor-shape]
select = "block"
insert = "bar"

[editor.lsp]
display-messages = true

[keys.normal]
"space" = { q = ":buffer-close" }
C-s = ":w" # Maps the Control-s to the typable command :w which is an alias for :write (save file)
C-o = ":open ~/.config/helix/config.toml" # Maps the Control-o to opening of the helix config file
g = { a = "code_action" } # Maps `ga` to show possible code actions
G = "goto_file_end" # Maps `G` to goto end of file
