[[language]]
name = "python"
language-server = {command = "/home/jp/.volta/bin/pyright" , config=""}


[[language]]
name = "lua"
scope = "source.lua"
file-types = ["lua"]
shebangs = ["lua"]
roots = []
comment-token = "--"
language-server = {command = "/home/jp/.local/bin/lua-language-server/bin/lua-language-server"}
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "latex"
file-types = ["tex"]
language-server = {command = "/home/jp/.local/bin/texlab"}
indent = { tab-width = 2, unit = "  " }
