[[language]]
name = "python"
language-server = {command = "/home/jp/.local/share/nvim/mason/bin/pyright" }

[[language]]
name = "latex"
file-types = ["tex"]
language-server = {command = "/home/jp/.local/share/nvim/mason/bin/texlab"}
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "typescript"
auto-format = true
language-server = {command = "/home/jp/.local/share/nvim/mason/bin/typescript-language-server" , args = ["--stdio"]}

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "(tsx)" # |typescript
file-types = ["tsx"]
roots = []
# TODO: highlights-params
language-server = { command = "typescript-language-server", args = ["--stdio"], language-id = "typescriptreact" }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "(js|javascript)"
file-types = ["js", "mjs", "cjs"]
shebangs = ["node"]
roots = []
comment-token = "//"
language-server = { command = "/home/jp/.local/share/nvim/mason/bin/typescript-language-server", args = ["--stdio"], language-id = "javascript" }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "haskell"
indent = {tab-width = 2,unit = "  "}
language-server = {command = "haskell-language-server-wrapper-1.8.0.0"}

[[language]]
name = "vue"
language-server = {command = "vue-language-server"}
