[[language]]
name = "python"
language-server = {command = "/home/jp/.local/share/nvim/mason/bin/pyright" }

[[language]]
name = "latex"
file-types = ["tex"]
language-server = {command = "/home/jp/.local/share/nvim/mason/bin/texlab"}
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "typescript"
auto-format = true
language-server = {command = "/home/jp/.local/share/nvim/mason/bin/typescript-language-server" , args = ["--stdio"]}

[[language]]
name = "haskell"
indent = {tab-width = 2,unit = "  "}
language-server = {command = "haskell-language-server-wrapper-1.8.0.0"}
