#! /bin/sh
color1="#BB9AF7"

pgrep -x sxhkd > /dev/null || sxhkd &

# Launch polybar
$HOME/.config/polybar/launch.sh

# Launch picom
pgrep -x picom > /dev/null || picom &

bspc monitor -d I II III IV V VI

bspc config border_width          3
bspc config focused_border_color  $color1
bspc config window_gap            6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2' follow=off state=monocle
bspc rule -a mpv desktop='^4'  state=monocle follow=on

feh --bg-fill --randomize $HOME/Imagens/wallpapers/
