#! /bin/sh
color1="#f7768e"

# Launch services first
pgrep -x picom > /dev/null || picom &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &

feh --bg-fill --randomize $HOME/Imagens/wallpapers/
# Launch polybar
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width          2
bspc config focused_border_color  $color1
bspc config window_gap            4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^3' follow=off 
bspc rule -a "Chromium-browser" desktop='^3' follow=off
bspc rule -a mpv desktop='^4'  state=monocle follow=on
bspc rule -a Inkscape desktop='^6'  state=monocle follow=off
