theme =  "pop-dark"

[editor]
idle-timeout = 20
completion-trigger-len = 0
line-number = "relative"
bufferline = "always"
cursorline = true
auto-format = true
color-modes = true
rulers = [80, 120]

[editor.cursor-shape]
select = "block"
insert = "bar"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner","file-name"]
center = ["workspace-diagnostics","version-control"]
right = ["diagnostics", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"

[keys.normal]
"0" = ["goto_line_start"]
"$" = ["goto_line_end"]
"esc" = ["collapse_selection","keep_primary_selection"]
"tab" = ["goto_next_buffer"]
"S-tab" = ["goto_previous_buffer"]
